<?php
/**
 * WorkItemResp
 *
 * PHP version 5
 *
 * @category Class
 * @package  Autodesk\Forge\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Autodesk\Forge\Client\Model;

use \ArrayAccess;

/**
 * WorkItemResp Class Doc Comment
 *
 * @category    Class
 * @package     Autodesk\Forge\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WorkItemResp implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     * @var string
     */
    protected static $swaggerModelName = 'work_item_resp';

    /**
     * Array of property to type mappings. Used for (de)serialization
     * @var string[]
     */
    protected static $swaggerTypes = [
        'id' => 'string',
        'arguments' => 'object',
        'status' => 'string',
        'status_detail' => 'object',
        'availability_zone' => 'string',
        'activity_id' => 'string',
        'version' => 'int',
        'timestamp' => 'string',
        'time_queued' => 'string',
        'time_input_transfer_started' => 'string',
        'time_script_started' => 'string',
        'time_script_ended' => 'string',
        'time_output_transfer_ended' => 'string',
        'bytes_tranferred_in' => 'int',
        'bytes_tranferred_out' => 'int',
    ];

    /**
     * @return \string[]
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'Id',
        'arguments' => 'Arguments',
        'status' => 'Status',
        'status_detail' => 'StatusDetail',
        'availability_zone' => 'AvailabilityZone',
        'activity_id' => 'ActivityId',
        'version' => 'Version',
        'timestamp' => 'Timestamp',
        'time_queued' => 'TimeQueued',
        'time_input_transfer_started' => 'TimeInputTransferStarted',
        'time_script_started' => 'TimeScriptStarted',
        'time_script_ended' => 'TimeScriptEnded',
        'time_output_transfer_ended' => 'TimeOutputTransferEnded',
        'bytes_tranferred_in' => 'BytesTranferredIn',
        'bytes_tranferred_out' => 'BytesTranferredOut',
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'arguments' => 'setArguments',
        'status' => 'setStatus',
        'status_detail' => 'setStatusDetail',
        'availability_zone' => 'setAvailabilityZone',
        'activity_id' => 'setActivityId',
        'version' => 'setVersion',
        'timestamp' => 'setTimestamp',
        'time_queued' => 'setTimeQueued',
        'time_input_transfer_started' => 'setTimeInputTransferStarted',
        'time_script_started' => 'setTimeScriptStarted',
        'time_script_ended' => 'setTimeScriptEnded',
        'time_output_transfer_ended' => 'setTimeOutputTransferEnded',
        'bytes_tranferred_in' => 'setBytesTranferredIn',
        'bytes_tranferred_out' => 'setBytesTranferredOut',
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'arguments' => 'getArguments',
        'status' => 'getStatus',
        'status_detail' => 'getStatusDetail',
        'availability_zone' => 'getAvailabilityZone',
        'activity_id' => 'getActivityId',
        'version' => 'getVersion',
        'timestamp' => 'getTimestamp',
        'time_queued' => 'getTimeQueued',
        'time_input_transfer_started' => 'getTimeInputTransferStarted',
        'time_script_started' => 'getTimeScriptStarted',
        'time_script_ended' => 'getTimeScriptEnded',
        'time_output_transfer_ended' => 'getTimeOutputTransferEnded',
        'bytes_tranferred_in' => 'getBytesTranferredIn',
        'bytes_tranferred_out' => 'getBytesTranferredOut',
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['arguments'] = isset($data['arguments']) ? $data['arguments'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['status_detail'] = isset($data['status_detail']) ? $data['status_detail'] : null;
        $this->container['availability_zone'] = isset($data['availability_zone']) ? $data['availability_zone'] : null;
        $this->container['activity_id'] = isset($data['activity_id']) ? $data['activity_id'] : null;
        $this->container['version'] = isset($data['version']) ? $data['version'] : null;
        $this->container['timestamp'] = isset($data['timestamp']) ? $data['timestamp'] : null;
        $this->container['time_queued'] = isset($data['time_queued']) ? $data['time_queued'] : null;
        $this->container['time_input_transfer_started'] = isset($data['time_input_transfer_started']) ? $data['time_input_transfer_started'] : null;
        $this->container['time_script_started'] = isset($data['time_script_started']) ? $data['time_script_started'] : null;
        $this->container['time_script_ended'] = isset($data['time_script_ended']) ? $data['time_script_ended'] : null;
        $this->container['time_output_transfer_ended'] = isset($data['time_output_transfer_ended']) ? $data['time_output_transfer_ended'] : null;
        $this->container['bytes_tranferred_in'] = isset($data['bytes_tranferred_in']) ? $data['bytes_tranferred_in'] : null;
        $this->container['bytes_tranferred_out'] = isset($data['bytes_tranferred_out']) ? $data['bytes_tranferred_out'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param string $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets arguments
     * @return object
     */
    public function getArguments()
    {
        return $this->container['arguments'];
    }

    /**
     * Sets arguments
     * @param object $arguments
     * @return $this
     */
    public function setArguments($arguments)
    {
        $this->container['arguments'] = $arguments;

        return $this;
    }

    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     * @param string $status
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets status_detail
     * @return object
     */
    public function getStatusDetail()
    {
        return $this->container['status_detail'];
    }

    /**
     * Sets status_detail
     * @param object $status_detail
     * @return $this
     */
    public function setStatusDetail($status_detail)
    {
        $this->container['status_detail'] = $status_detail;

        return $this;
    }

    /**
     * Gets availability_zone
     * @return string
     */
    public function getAvailabilityZone()
    {
        return $this->container['availability_zone'];
    }

    /**
     * Sets availability_zone
     * @param string $availability_zone
     * @return $this
     */
    public function setAvailabilityZone($availability_zone)
    {
        $this->container['availability_zone'] = $availability_zone;

        return $this;
    }

    /**
     * Gets activity_id
     * @return string
     */
    public function getActivityId()
    {
        return $this->container['activity_id'];
    }

    /**
     * Sets activity_id
     * @param string $activity_id
     * @return $this
     */
    public function setActivityId($activity_id)
    {
        $this->container['activity_id'] = $activity_id;

        return $this;
    }

    /**
     * Gets version
     * @return int
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     * @param int $version
     * @return $this
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets timestamp
     * @return string
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     * @param string $timestamp
     * @return $this
     */
    public function setTimestamp($timestamp)
    {
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets time_queued
     * @return string
     */
    public function getTimeQueued()
    {
        return $this->container['time_queued'];
    }

    /**
     * Sets time_queued
     * @param string $time_queued
     * @return $this
     */
    public function setTimeQueued($time_queued)
    {
        $this->container['time_queued'] = $time_queued;

        return $this;
    }

    /**
     * Gets time_input_transfer_started
     * @return string
     */
    public function getTimeInputTransferStarted()
    {
        return $this->container['time_input_transfer_started'];
    }

    /**
     * Sets time_input_transfer_started
     * @param string $time_input_transfer_started
     * @return $this
     */
    public function setTimeInputTransferStarted($time_input_transfer_started)
    {
        $this->container['time_input_transfer_started'] = $time_input_transfer_started;

        return $this;
    }

    /**
     * Gets time_script_started
     * @return string
     */
    public function getTimeScriptStarted()
    {
        return $this->container['time_script_started'];
    }

    /**
     * Sets time_script_started
     * @param string $time_script_started
     * @return $this
     */
    public function setTimeScriptStarted($time_script_started)
    {
        $this->container['time_script_started'] = $time_script_started;

        return $this;
    }

    /**
     * Gets time_script_ended
     * @return string
     */
    public function getTimeScriptEnded()
    {
        return $this->container['time_script_ended'];
    }

    /**
     * Sets time_script_ended
     * @param string $time_script_ended
     * @return $this
     */
    public function setTimeScriptEnded($time_script_ended)
    {
        $this->container['time_script_ended'] = $time_script_ended;

        return $this;
    }

    /**
     * Gets time_output_transfer_ended
     * @return string
     */
    public function getTimeOutputTransferEnded()
    {
        return $this->container['time_output_transfer_ended'];
    }

    /**
     * Sets time_output_transfer_ended
     * @param string $time_output_transfer_ended
     * @return $this
     */
    public function setTimeOutputTransferEnded($time_output_transfer_ended)
    {
        $this->container['time_output_transfer_ended'] = $time_output_transfer_ended;

        return $this;
    }

    /**
     * Gets bytes_tranferred_in
     * @return int
     */
    public function getBytesTranferredIn()
    {
        return $this->container['bytes_tranferred_in'];
    }

    /**
     * Sets bytes_tranferred_in
     * @param int $bytes_tranferred_in
     * @return $this
     */
    public function setBytesTranferredIn($bytes_tranferred_in)
    {
        $this->container['bytes_tranferred_in'] = $bytes_tranferred_in;

        return $this;
    }

    /**
     * Gets bytes_tranferred_out
     * @return int
     */
    public function getBytesTranferredOut()
    {
        return $this->container['bytes_tranferred_out'];
    }

    /**
     * Sets bytes_tranferred_out
     * @param int $bytes_tranferred_out
     * @return $this
     */
    public function setBytesTranferredOut($bytes_tranferred_out)
    {
        $this->container['bytes_tranferred_out'] = $bytes_tranferred_out;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Autodesk\Forge\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Autodesk\Forge\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


