<?php
/**
 * FormatsFormatsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Autodesk\Forge\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Autodesk\Forge\Client;

/**
 * FormatsFormatsTest Class Doc Comment
 *
 * @category    Class
 */
// * @description FormatsFormats
/**
 * @package     Autodesk\Forge\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FormatsFormatsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "FormatsFormats"
     */
    public function testFormatsFormats()
    {

    }

    /**
     * Test attribute "svf"
     */
    public function testPropertySvf()
    {

    }

    /**
     * Test attribute "thumbnail"
     */
    public function testPropertyThumbnail()
    {

    }

    /**
     * Test attribute "stl"
     */
    public function testPropertyStl()
    {

    }

    /**
     * Test attribute "step"
     */
    public function testPropertyStep()
    {

    }

    /**
     * Test attribute "iges"
     */
    public function testPropertyIges()
    {

    }

    /**
     * Test attribute "obj"
     */
    public function testPropertyObj()
    {

    }

}
