<?php
/**
 * JsonApiLinksPagingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Autodesk\Forge\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Autodesk\Forge\Client;

/**
 * JsonApiLinksPagingTest Class Doc Comment
 *
 * @category    Class
 */
// * @description provides the links used for paging
/**
 * @package     Autodesk\Forge\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JsonApiLinksPagingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "JsonApiLinksPaging"
     */
    public function testJsonApiLinksPaging()
    {

    }

    /**
     * Test attribute "first"
     */
    public function testPropertyFirst()
    {

    }

    /**
     * Test attribute "prev"
     */
    public function testPropertyPrev()
    {

    }

    /**
     * Test attribute "next"
     */
    public function testPropertyNext()
    {

    }

    /**
     * Test attribute "last"
     */
    public function testPropertyLast()
    {

    }

}
