<?php
/**
 * UserProfileProfileImagesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Autodesk\Forge\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Autodesk\Forge\Client;

/**
 * UserProfileProfileImagesTest Class Doc Comment
 *
 * @category    Class
 */
// * @description A flat JSON object of attribute-value pairs in which the attributes specify available profile image sizes in the format sizeX&lt;pixels&gt; (where &lt;pixels&gt; is an integer that represents both height and width in pixels of square profile images) and the values are URLs for downloading the images via HTTP
/**
 * @package     Autodesk\Forge\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserProfileProfileImagesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "UserProfileProfileImages"
     */
    public function testUserProfileProfileImages()
    {

    }

    /**
     * Test attribute "size_x20"
     */
    public function testPropertySizeX20()
    {

    }

    /**
     * Test attribute "size_x40"
     */
    public function testPropertySizeX40()
    {

    }

    /**
     * Test attribute "size_x50"
     */
    public function testPropertySizeX50()
    {

    }

    /**
     * Test attribute "size_x58"
     */
    public function testPropertySizeX58()
    {

    }

    /**
     * Test attribute "size_x80"
     */
    public function testPropertySizeX80()
    {

    }

    /**
     * Test attribute "size_x120"
     */
    public function testPropertySizeX120()
    {

    }

    /**
     * Test attribute "size_x160"
     */
    public function testPropertySizeX160()
    {

    }

    /**
     * Test attribute "size_x176"
     */
    public function testPropertySizeX176()
    {

    }

    /**
     * Test attribute "size_x240"
     */
    public function testPropertySizeX240()
    {

    }

    /**
     * Test attribute "size_x360"
     */
    public function testPropertySizeX360()
    {

    }

}
