<?php
/**
 * ActivitiesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Autodesk\Forge\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Autodesk\Forge\Client;

use \Autodesk\Forge\Client\Configuration;
use \Autodesk\Forge\Client\ApiClient;
use \Autodesk\Forge\Client\ApiException;
use \Autodesk\Forge\Client\ObjectSerializer;

/**
 * ActivitiesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Autodesk\Forge\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ActivitiesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createActivity
     *
     * Creates a new Activity..
     *
     */
    public function testCreateActivity()
    {

    }

    /**
     * Test case for deleteActivity
     *
     * Removes a specific Activity..
     *
     */
    public function testDeleteActivity()
    {

    }

    /**
     * Test case for deleteActivityHistory
     *
     * Removes the version history of the specified Activity..
     *
     */
    public function testDeleteActivityHistory()
    {

    }

    /**
     * Test case for getActivity
     *
     * Returns the details of a specific Activity..
     *
     */
    public function testGetActivity()
    {

    }

    /**
     * Test case for getActivityVersions
     *
     * Returns all old versions of a specified Activity..
     *
     */
    public function testGetActivityVersions()
    {

    }

    /**
     * Test case for getAllActivities
     *
     * Returns the details of all Activities..
     *
     */
    public function testGetAllActivities()
    {

    }

    /**
     * Test case for patchActivity
     *
     * Updates an Activity by specifying only the changed attributes..
     *
     */
    public function testPatchActivity()
    {

    }

    /**
     * Test case for setActivityVersion
     *
     * Sets the Activity to the specified version..
     *
     */
    public function testSetActivityVersion()
    {

    }

}
