<?php
/**
 * AppPackagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Autodesk\Forge\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Autodesk\Forge\Client;

use \Autodesk\Forge\Client\Configuration;
use \Autodesk\Forge\Client\ApiClient;
use \Autodesk\Forge\Client\ApiException;
use \Autodesk\Forge\Client\ObjectSerializer;

/**
 * AppPackagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Autodesk\Forge\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppPackagesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createAppPackage
     *
     * Creates an AppPackage module..
     *
     */
    public function testCreateAppPackage()
    {

    }

    /**
     * Test case for deleteAppPackage
     *
     * Removes a specific AppPackage..
     *
     */
    public function testDeleteAppPackage()
    {

    }

    /**
     * Test case for deleteAppPackageHistory
     *
     * Removes the version history of the specified AppPackage..
     *
     */
    public function testDeleteAppPackageHistory()
    {

    }

    /**
     * Test case for getAllAppPackages
     *
     * Returns the details of all AppPackages..
     *
     */
    public function testGetAllAppPackages()
    {

    }

    /**
     * Test case for getAppPackage
     *
     * Returns the details of a specific AppPackage..
     *
     */
    public function testGetAppPackage()
    {

    }

    /**
     * Test case for getAppPackageVersions
     *
     * Returns all old versions of a specified AppPackage..
     *
     */
    public function testGetAppPackageVersions()
    {

    }

    /**
     * Test case for getUploadUrl
     *
     * Requests a pre-signed URL for uploading a zip file that contains the binaries for this AppPackage..
     *
     */
    public function testGetUploadUrl()
    {

    }

    /**
     * Test case for getUploadUrlWithRequireContentType
     *
     * Requests a pre-signed URL for uploading a zip file that contains the binaries for this AppPackage. Unlike the GetUploadUrl method that takes no parameters, this method allows the client to request that the pre-signed URL to be issued so that the subsequent HTTP PUT operation will require Content-Type=binary/octet-stream..
     *
     */
    public function testGetUploadUrlWithRequireContentType()
    {

    }

    /**
     * Test case for patchAppPackage
     *
     * Updates an AppPackage by specifying only the changed attributes..
     *
     */
    public function testPatchAppPackage()
    {

    }

    /**
     * Test case for setAppPackageVersion
     *
     * Sets the AppPackage to the specified version..
     *
     */
    public function testSetAppPackageVersion()
    {

    }

    /**
     * Test case for updateAppPackage
     *
     * Updates an AppPackage by redefining the entire Activity object..
     *
     */
    public function testUpdateAppPackage()
    {

    }

}
