<?php
/**
 * DerivativesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Autodesk\Forge\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Autodesk\Forge\Client;

use \Autodesk\Forge\Client\Configuration;
use \Autodesk\Forge\Client\ApiClient;
use \Autodesk\Forge\Client\ApiException;
use \Autodesk\Forge\Client\ObjectSerializer;

/**
 * DerivativesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Autodesk\Forge\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DerivativesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for deleteManifest
     *
     * .
     *
     */
    public function testDeleteManifest()
    {

    }

    /**
     * Test case for getDerivativeManifest
     *
     * .
     *
     */
    public function testGetDerivativeManifest()
    {

    }

    /**
     * Test case for getFormats
     *
     * .
     *
     */
    public function testGetFormats()
    {

    }

    /**
     * Test case for getManifest
     *
     * .
     *
     */
    public function testGetManifest()
    {

    }

    /**
     * Test case for getMetadata
     *
     * .
     *
     */
    public function testGetMetadata()
    {

    }

    /**
     * Test case for getModelviewMetadata
     *
     * .
     *
     */
    public function testGetModelviewMetadata()
    {

    }

    /**
     * Test case for getModelviewProperties
     *
     * .
     *
     */
    public function testGetModelviewProperties()
    {

    }

    /**
     * Test case for getThumbnail
     *
     * .
     *
     */
    public function testGetThumbnail()
    {

    }

    /**
     * Test case for translate
     *
     * .
     *
     */
    public function testTranslate()
    {

    }

}
